get http://localhost:8080/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YzcwZmUzYS04M2M3LTQ5NDItOTYxZC02MmE3YmZiYTYyMjciLCJpYXQiOjE2Mjk5ODAwOTYsImV4cCI6MTYyOTk4NzI5Nn0.YXj1Ktwq1j8S0YJH4APldizmCP7yvK2_VBMEZWF5Lf0