POST http://localhost:8080/auth/refresh HTTP/1.1
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYThlNTEwMS0xNDc5LTRiMzYtODczYi05MGEzOTNhMzBhYTYiLCJpYXQiOjE2MzAyNDQyMTgsImV4cCI6MTYzMDg0OTAxOH0.srbTpPUYi9MqS0wqcX4EBxrmnSzbK7bVGLrpy4mi4Q0"
}