POST http://localhost:8080/admin/post HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYThlNTEwMS0xNDc5LTRiMzYtODczYi05MGEzOTNhMzBhYTYiLCJpYXQiOjE2MzAyNDg4NjIsImV4cCI6MTYzMDI1NjA2Mn0.BE5i9Hk-rxj1y6vHt2O0E1tSz7N9nYo4fHsL9OEKr-A
content-type: application/json

{
    "hello": "hello"
}